apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-creds
  namespace: cloudflared
type: Opaque
stringData:
  credentials.json: |
    {"AccountTag":"CHANGE_ME","TunnelID":"CHANGE_ME","TunnelSecret":"CHANGE_ME"}
