# Placeholder. The seal script overwrites this file.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-minio
  namespace: app
spec:
  encryptedData: {}
  template:
    metadata:
      name: app-minio
      namespace: app
