apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-backups
  namespace: app
  labels:
    app.kubernetes.io/name: postgres-backup
    app.kubernetes.io/part-of: app
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  storageClassName: local-static
  volumeName: app-backups
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
