apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: app
  labels:
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/part-of: app
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: meilisearch
  ports:
    - name: http
      port: 7700
      targetPort: http
